import Image from "next/image";

export default function PrivacyPolicy() {
  return (
    <div className="min-h-screen flex justify-center items-center bg-[#020A13] p-6">
      <div className="max-w-3xl w-full bg-[#0D1B2A] shadow-lg rounded-lg p-6 text-white">
        {/* Logo and App Name */}
        <div className="flex flex-col items-center mb-6">
          <Image
            src="/logo.png" // Ensure this is placed in the public folder
            alt="Keeper Logo"
            width={100}
            height={100}
            className="mb-2"
          />
          <h1 className="text-3xl font-bold text-white">Keeper</h1>
        </div>

        <h2 className="text-2xl font-semibold text-gray-200 mb-4">
          Privacy Policy
        </h2>
        <p className="text-gray-300 mb-4">
          This privacy policy applies to the <strong>Keeper</strong> app (hereby
          referred to as "Application") for mobile devices that was created by
          Tapan Patel (hereby referred to as "Service Provider") as a Free
          service. This service is intended for use "AS IS".
        </p>

        <h3 className="text-xl font-semibold text-gray-200 mt-6 mb-2">
          Information Collection and Use
        </h3>
        <p className="text-gray-300 mb-2">
          The Application collects information when you download and use it.
          This information may include:
        </p>
        <ul className="list-disc list-inside text-gray-300 mb-4">
          <li>Your device’s Internet Protocol address (e.g., IP address)</li>
          <li>
            The pages of the Application that you visit, the time and date of
            your visit, and time spent
          </li>
          <li>The operating system you use on your mobile device</li>
        </ul>

        <h3 className="text-xl font-semibold text-gray-200 mt-6 mb-2">
          Third-Party Access
        </h3>
        <p className="text-gray-300 mb-4">
          The Application uses third-party services that may collect data. Below
          are the privacy policies of these services:
        </p>
        <ul className="list-disc list-inside text-blue-400 mb-4">
          <li>
            <a
              href="https://www.google.com/policies/privacy/"
              target="_blank"
              rel="noopener noreferrer"
            >
              Google Play Services
            </a>
          </li>
          <li>
            <a
              href="https://expo.io/privacy"
              target="_blank"
              rel="noopener noreferrer"
            >
              Expo
            </a>
          </li>
        </ul>

        <h3 className="text-xl font-semibold text-gray-200 mt-6 mb-2">
          Opt-Out Rights
        </h3>
        <p className="text-gray-300 mb-4">
          You can stop all collection of information by uninstalling the
          application.
        </p>

        <h3 className="text-xl font-semibold text-gray-200 mt-6 mb-2">
          Children
        </h3>
        <p className="text-gray-300 mb-4">
          The Service Provider does not knowingly collect personal data from
          children under 13 years of age. If discovered, it will be deleted
          immediately.
        </p>

        <h3 className="text-xl font-semibold text-gray-200 mt-6 mb-2">
          Security
        </h3>
        <p className="text-gray-300 mb-4">
          The Service Provider provides safeguards to protect the
          confidentiality of your information.
        </p>

        <h3 className="text-xl font-semibold text-gray-200 mt-6 mb-2">
          Changes
        </h3>
        <p className="text-gray-300 mb-4">
          This Privacy Policy may be updated from time to time. You are advised
          to review it periodically.
        </p>

        <h3 className="text-xl font-semibold text-gray-200 mt-6 mb-2">
          Contact Us
        </h3>
        <p className="text-gray-300 mb-4">
          If you have any questions regarding this Privacy Policy, contact the
          Service Provider at{" "}
          <a href="mailto:tapan2930@gmail.com" className="text-blue-400">
            tapan2930@gmail.com
          </a>
          .
        </p>

        <hr className="my-6 border-gray-600" />
        <p className="text-gray-400 text-sm">
          This privacy policy page was generated by{" "}
          <a
            href="https://app-privacy-policy-generator.nisrulz.com/"
            target="_blank"
            rel="noopener noreferrer"
            className="text-blue-400"
          >
            App Privacy Policy Generator
          </a>
          .
        </p>
      </div>
    </div>
  );
}
